name: Deploy to GoDaddy VPS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.4'

    # Setup SSH
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/encoded_key
        base64 -d /tmp/encoded_key > ~/.ssh/id_rsa
        rm /tmp/encoded_key
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    # Deploy to VPS
    - name: Deploy to VPS
      run: |
        ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} '
          # Create temporary directory
          TEMP_DIR=$(mktemp -d)
          echo "Created temporary directory: $TEMP_DIR"

          # Clone repository
          git clone https://github.com/codeinwind/scientism-poetry.git $TEMP_DIR
          cd $TEMP_DIR

          # Make scripts executable
          chmod +x deploy/scripts/*.sh

          # Setup Node.js version
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18.20.4
          nvm use 18.20.4
          nvm alias default 18.20.4
          
          # Verify Node.js version
          echo "Node.js version:"
          node -v
          
          # Run deployment scripts
          echo "Running frontend setup..."
          ./deploy/scripts/setup-frontend.sh "${{ secrets.REACT_APP_API_URL }}" || exit 1

          echo "Running backend setup..."
          ./deploy/scripts/setup-backend.sh "${{ secrets.BACKEND_PORT }}" "${{ secrets.MONGODB_URI }}" "${{ secrets.JWT_SECRET }}" || exit 1

          # Configure PM2 to use Node.js 18.20.4
          echo "Configuring PM2..."
          pm2 kill || true
          PM2_EXEC_PATH=$(which node)
          echo "PM2 will use Node.js from: $PM2_EXEC_PATH"

          # Start backend with specific Node.js version
          cd /var/www/scientism-poetry/backend
          echo "Starting backend with Node.js $(node -v)..."
          pm2 delete scientism-poetry-backend || true
          pm2 start server.js --name scientism-poetry-backend --interpreter $PM2_EXEC_PATH
          pm2 save

          # Verify PM2 process
          echo "PM2 process status:"
          pm2 list

          # Cleanup
          cd /
          rm -rf $TEMP_DIR
          echo "Deployment completed successfully!"
        '

    # Verify deployment
    - name: Verify deployment
      run: |
        ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "
          echo \"=== Node.js Version ===\"
          export NVM_DIR=\"\$HOME/.nvm\"
          [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"
          nvm use 18.20.4 > /dev/null 2>&1
          node -v

          echo \"\n=== PM2 Process Status ===\"
          pm2 list

          echo \"\n=== API Health Check ===\"
          curl -s http://localhost:5000/api/health || echo \"API health check failed\"

          echo \"\n=== Log Directory Contents ===\"
          ls -la /var/log/scientism-poetry || echo \"Log directory check failed\"

          echo \"\n=== Frontend Env Files ===\"
          ls -la /var/www/scientism-poetry/frontend/.env* || echo \"Frontend env files check failed\"

          echo \"\n=== Verification Complete ===\"
        "
