name: Deploy to GoDaddy VPS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Test build on GitHub Actions
    - name: Test Frontend Build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      run: |
        cd frontend
        npm ci
        npm run build
        cd ..

    # Test backend
    - name: Test Backend
      run: |
        cd backend
        npm ci
        cd ..

    # Setup SSH
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        # Write the base64 encoded key to a temporary file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/encoded_key
        # Decode the key and save it properly
        base64 -d /tmp/encoded_key > ~/.ssh/id_rsa
        # Clean up encoded file
        rm /tmp/encoded_key
        # Set proper permissions
        chmod 600 ~/.ssh/id_rsa
        # Add host to known_hosts
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    # Deploy to VPS
    - name: Deploy to VPS
      run: |
        ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} '
          # Create temporary directory
          TEMP_DIR=$(mktemp -d) &&
          echo "Created temporary directory: $TEMP_DIR" &&

          # Clone repository to temporary directory
          git clone https://github.com/codeinwind/scientism-poetry.git $TEMP_DIR &&
          cd $TEMP_DIR &&

          # Build frontend
          echo "Building frontend..." &&
          cd frontend &&
          npm ci &&
          npm run build &&
          cd .. &&

          # Build backend
          echo "Building backend..." &&
          cd backend &&
          npm ci --production &&
          cd .. &&

          # If builds are successful, stop the current service and update production
          echo "Updating production..." &&
          
          # Stop existing PM2 processes
          pm2 stop scientism-poetry-backend || true &&
          pm2 delete scientism-poetry-backend || true &&

          # Update production directories
          sudo rm -rf /var/www/scientism-poetry/frontend/* &&
          sudo rm -rf /var/www/scientism-poetry/backend/* &&
          
          sudo cp -r frontend/build/* /var/www/scientism-poetry/frontend/ &&
          sudo cp -r backend/* /var/www/scientism-poetry/backend/ &&

          # Recreate the symbolic link after deployment
          sudo ln -s /var/www/scientism-poetry/env/.env /var/www/scientism-poetry/backend/.env


          # Start backend with PM2
          cd /var/www/scientism-poetry/backend &&
          pm2 start server.js --name scientism-poetry-backend &&

          # Reload Nginx
          sudo systemctl reload nginx &&

          # Cleanup
          cd / &&
          rm -rf $TEMP_DIR &&

          echo "Deployment completed successfully!"
        '

    # Verify deployment
    - name: Verify deployment
      run: |
        ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} '
          echo "Checking PM2 status:" &&
          pm2 list &&
          echo "Checking API health:" &&
          curl -s http://localhost:5000/api/health &&
          echo "Deployment verification complete"
        '
